version: '3.1'

services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: todo-db-password
      POSTGRES_DB: todo
    ports:
      - 6432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
